name: 'Build exporter'
description: 'Build and release an exporter'
inputs: 
  exporter:
    description: 'Exporter name'
    required: true
    default: ''
  artifactory_token:
    description: 'Artifactory token'
    required: true
    default: ''
  artifactory_username:
    description: 'Artifactory username'
    required: true
    default: ''
  tag_name:
    description: 'Tag name'
    required: true
    default: ''
  target:
    description: 'Target name'
    required: false
    default: ''
  sysdig_secure_token:
    description: 'Sysdig Secure token'
    required: true
    default: ''
  dockerfile:
    description: 'Dockerfile destination'
    required: false
    default: 'Dockerfile'
  repository:
    description: 'Repository url'
    required: true
    default: ''
branding:
  color: 'green'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@master
    - name: Login to Artifactory
      uses: docker/login-action@v1 
      with:
        registry: ${{ inputs.repository }}
        username: ${{ inputs.artifactory_username }}
        password: ${{ inputs.artifactory_token }}
    - name: Build image
      shell: bash
      run: |
        docker build --label release=${{ inputs.tag_name }} -f ${{ inputs.dockerfile }} --target ${{ inputs.target }} -t ${{ inputs.repository }}/${{ inputs.exporter }}:latest .
    - name: Publish docker image
      if: ${{ inputs.target }} == 'ubi'
      shell: bash
      run: |
        docker tag ${{ inputs.repository }}/${{ inputs.exporter }}:latest ${{ inputs.repository }}/${{ inputs.exporter }}:${{ inputs.tag_name }}-${{ inputs.target }}
        docker push ${{ inputs.repository }}/${{ inputs.exporter }}:${{ inputs.tag_name }}-${{ inputs.target }}
        docker push ${{ inputs.repository }}/${{ inputs.exporter }}:latest
    - name: Publish docker image
      if: ${{ inputs.target }} != 'ubi'
      shell: bash
      run: |
        docker tag ${{ inputs.repository }}/${{ inputs.exporter }}:latest ${{ inputs.repository }}/${{ inputs.exporter }}:${{ inputs.tag_name }}
        docker push ${{ inputs.repository }}/${{ inputs.exporter }}:${{ inputs.tag_name }}