name: 'Build exporter'
description: 'Build and release an exporter'
inputs: 
  exporter:
    description: 'Exporter name'
    required: true
    default: ''
  artifactory_token:
    description: 'Artifactory token'
    required: true
    default: ''
  artifactory_username:
    description: 'Artifactory username'
    required: true
    default: ''
  tag_name:
    description: 'Tag name'
    required: true
    default: ''
  target:
    description: 'Target name'
    required: false
    default: ''
  sysdig_secure_token:
    description: 'Sysdig Secure token'
    required: true
    default: ''
  dockerfile:
    description: 'Dockerfile destination'
    required: false
    default: 'Dockerfile'
branding:
  color: 'green'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@master
    - name: Login to Artifactory
      uses: docker/login-action@v1 
      with:
        registry: artifactory.internal.sysdig.com
        username: ${{ inputs.artifactory_username }}
        password: ${{ inputs.artifactory_token }}
    - name: Build image
      run: |
        docker build --label release=${{ inputs.tag_name }} -f ${{ inputs.dockerfile }} --target ${{ input.target }} -t artifactory.internal.sysdig.com/${{ inputs.exporter }}:latest .
    - name: Publish docker image
      if: ${{ inputs.target }} == 'ubi'
      run: |
        docker tag artifactory.internal.sysdig.com/${{ inputs.exporter }}:latest artifactory.internal.sysdig.com/${{ inputs.exporter }}:${{ inputs.tag_name }}-${{ input.target }}
        docker push artifactory.internal.sysdig.com/${{ inputs.exporter }}:${{ inputs.tag_name }}-${{ input.target }}
    - name: Publish docker image
      if: ${{ inputs.target }} != 'ubi'
      run: |
        docker tag artifactory.internal.sysdig.com/${{ inputs.exporter }}:latest artifactory.internal.sysdig.com/${{ inputs.exporter }}:${{ inputs.tag_name }}
        docker push artifactory.internal.sysdig.com/${{ inputs.exporter }}:${{ inputs.tag_name }}
        docker push artifactory.internal.sysdig.com/${{ inputs.exporter }}:latest